name: Deploy Agri-Price Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: "us-east-1"
  STACK_NAME: "agri-price-pipeline-stack"
  S3_BUCKET: "agri-price-dev-raw-project"
  ARTIFACT_BUCKET: "agri-artifacts"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          python-version: '3.14'

      

      # If you always use temporary creds, keep aws-session-token.
      # If not, this conditional setup avoids failure when token is absent.
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}      

      - name: Validate CloudFormation Template
        working-directory: ./infrastructure
        run: |
          aws cloudformation validate-template --template-body file://template.yaml

      - name: Package CloudFormation Template
        working-directory: ./infrastructure
        run: |
          aws cloudformation package \
            --template-file template.yaml \
            --s3-bucket ${{ env.ARTIFACT_BUCKET }} \
            --output-template-file packaged-template.yaml

      - name: Deploy CloudFormation Stack
        working-directory: ./infrastructure
        run: |
          aws cloudformation deploy \
            --template-file packaged-template.yaml \
            --stack-name ${{ env.STACK_NAME }} \
            --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
            --no-fail-on-empty-changeset

      - name: Deploy Frontend to S3 (Static Website)
        run: |
          aws s3 sync ./src/frontend s3://${{ env.S3_BUCKET }}/site/ \
            --delete \
            --exact-timestamps

      - name: Run SageMaker Setup Script
        run: |
          pip install sagemaker boto3
          python ./src/sagemaker_code/training_pipeline.py